apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  path: ./flux/apps/observability/kube-state-metrics/app
  prune: true
  targetNamespace: observability
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: prometheus-crds
