apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: api-jwt
  namespace: fluence
spec:
  jwt:
    optional: false
    providers:
      - name: authentik
        issuer: https://authentik.${NETWORK}.cloudless.dev/application/o/jwks
        remoteJWKS:
          uri: https://authentic.${NETWORK}.cloudless.dev/application/o/jwks/jwks
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: api
