apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crd-operator
spec:
  chart:
    spec:
      chart: ./charts/crd-operator
      sourceRef:
        kind: GitRepository
        name: lightmare
        namespace: fluence
      interval: 1m
      reconcileStrategy: Revision
