apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crd-operator
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/fluence/crd-operator/app/overlays/${NETWORK}
  prune: false
  targetNamespace: fluence
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: spectrum-vars
        optional: false
      - kind: ConfigMap
        name: spectrum-manual-vars
        optional: true
  dependsOn:
    - name: envoy
    - name: kube-ovn-fluence-network
    - name: envoy-proxy
