apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator-crd
  namespace: flux-system
spec:
  path: ./flux/apps/storage/piraeus-operator/crd
  prune: false
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  path: ./flux/apps/storage/piraeus-operator/app
  prune: false
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: piraeus-operator-crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linstor-cluster
  namespace: flux-system
spec:
  path: ./flux/apps/storage/piraeus-operator/cluster
  prune: false
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: piraeus-operator-crd
    - name: piraeus-operator
