apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/kubevirt/kubevirt/app
  prune: true
  targetNamespace: kubevirt
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
