{
 "title": "CRD Operator Logs",
 "tags": [
  "logs",
  "crd-operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "controller,api,admission-controller"
   },
   { "name": "level", "query": "ERROR,WARN,INFO" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "namespace:fluence AND container:($container) | stats by (level) count(*) as hits"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "namespace:fluence AND container:($container) AND level:ERROR"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "namespace:fluence AND container:($container) AND level:($level)"
    }
   ]
  }
 ]
}