apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubevirt-virt-api-recording
spec:
  groups:
    - name: kubevirt.virt_api.recording_rules
      interval: 30s
      rules:
      - record: kubevirt_virt_api_up
        expr: sum(kube_pod_status_phase{pod=~'virt-api-.*', phase="Running", namespace='kubevirt'}) or vector(0)
