apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  name: spectrum-${NETWORK}-access
spec:
  name: "spectrum-${NETWORK}-access"
  description: "Allow dev and devops access to spectrum-${NETWORK} resources"
  sourceGroups:
    - dev
    - devops
  destinationGroups:
    - spectrum-${NETWORK}
  bidirectional: false
  protocols:
    - tcp
