apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  annotations:
    alpha.kubevirt.io/EmulatorThreadCompleteToEvenParity: ""
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - CPUManager
        - AlignCPUs
        - NUMA
        - ExpandDisk
