apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.1/kubevirt-operator.yaml
patches:
  - target:
      kind: Namespace
      name: kubevirt
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kubevirt
      $patch: delete
