apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller
  labels:
    app.kubernetes.io/name: controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
