apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator-crds
spec:
  interval: 10m
  path: ./config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: piraeus-operator
