apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: crd-operator-logs
  labels:
    rule-type: vlogs
spec:
  groups:
    - name: crd-controller-logs
      type: vlogs
      interval: "30s"
      params:
        query:
          - "container:controller AND namespace:fluence"
      rules:
        - alert: CrdControllerErrorLogs
          expr: '* | unpack_json | filter level:(ERROR OR WARN) | stats by (level) count(*) as hits | filter hits:>0'
          for: 0s
          annotations:
            summary: "crd-controller {{ $labels.level }} logs detected"
            description: "crd-controller has {{ $value }} {{ $labels.level }} log entries in the last 30s"
          labels:
            severity: warning
    - name: crd-api-logs
      type: vlogs
      interval: "30s"
      params:
        query:
          - "container:api AND namespace:fluence"
      rules:
        - alert: CrdApiErrorLogs
          expr: '* | unpack_json | filter level:(ERROR OR WARN) | stats by (level) count(*) as hits | filter hits:>0'
          for: 0s
          annotations:
            summary: "crd-api {{ $labels.level }} logs detected"
            description: "crd-api has {{ $value }} {{ $labels.level }} log entries in the last 30s"
          labels:
            severity: warning
    - name: crd-admission-logs
      type: vlogs
      interval: "30s"
      params:
        query:
          - "container:admission-controller AND namespace:fluence"
      rules:
        - alert: CrdAdmissionErrorLogs
          expr: '* | unpack_json | filter level:(ERROR OR WARN) | stats by (level) count(*) as hits | filter hits:>0'
          for: 0s
          annotations:
            summary: "crd-admission {{ $labels.level }} logs detected"
            description: "crd-admission has {{ $value }} {{ $labels.level }} log entries in the last 30s"
          labels:
            severity: warning
