apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: stack-logs
spec:
  replicaCount: 1
  externalLabels:
    cluster_id: "${CLUSTER_ID}"
    network: ${NETWORK}
  datasource:
    url: "http://vlogs-stack.observability.svc:9428"
  notifier:
    url: "http://vmalertmanager-stack.observability.svc:9093"
  evaluationInterval: "30s"
  selectAllByDefault: false
  ruleSelector:
    matchLabels:
      rule-type: vlogs
  remoteWrite:
    url: "http://vmsingle-stack.observability.svc:8429"
