apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lightmare
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/lightmare/lightmare/app/overlays/${NETWORK}
  prune: false
  targetNamespace: lightmare
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: kubevirt
    - name: kube-ovn
