apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: lightmare
  values:
    operator:
      octopus: true
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.7.11@sha256:7dbd5ecc90f41261326ddd156bfafa6e27373c71724f096893625a138f8475c9"
      config:
        k8s:
          cni: "ovn"
          publicNetwork: "public"
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.17.0@sha256:e2704500147b4c385e1047728e8158c6e6614a519ab8c0bd27eae79aece8d2f1"
          memory: 2.48 gib
        chainAdapter:
          ipfsGatewayEndpoint: https://ipfs-gateway.fluence.dev
          privateRPCTokenSecretRef: ${PRIVATE_RPC_TOKEN:=null}
