apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: lightmare
  values:
    operator:
      octopus: true
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.7.11@sha256:7dbd5ecc90f41261326ddd156bfafa6e27373c71724f096893625a138f8475c9"
      config:
        k8s:
          cni: "ovn"
          publicNetwork: "kube-system/public"
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.16.12@sha256:82699d5fe834175c911fc064223ff09810a33274d12a6ac355dc36fdbd4743b6"
          memory: 2.48 gib
        chainAdapter:
          ipfsGatewayEndpoint: https://ipfs-gateway.fluence.dev
          privateRPCTokenSecretRef: ${PRIVATE_RPC_TOKEN:=null}
