apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: lightmare
    namespace: lightmare
  values:
    operator:
      octopus: true
      image:
        repository: "fluencelabs/lightmare"
        tag: "0.7.6@sha256:4ca024e7f9ce105fdeb5732d1bb668c8bc1f80c66734b855f480ec1673eb94c6"
      config:
        k8s:
          cni: "ovn"
          publicNetwork: "kube-system/public"
        ccp:
          image:
            repository: "fluencelabs/ccp-cu-worker"
            tag: "0.17.0@sha256:e2704500147b4c385e1047728e8158c6e6614a519ab8c0bd27eae79aece8d2f1"
          memory: 2.48 gib
        chainAdapter:
          ipfsGatewayEndpoint: https://ipfs-gateway.fluence.dev
