apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  path: ./flux/apps/local-path-provisioner/local-path-provisioner/app
  prune: true
  targetNamespace: local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
