apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: alloy-operator
    namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      deployAlloyCRD: true
      deployPodLogsCRD: true
