apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy-operator
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    crds:
      deployAlloyCRD: true
      deployPodLogsCRD: true
