apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
  namespace: lightmare
spec:
  values:
    operator:
      config:
        chainAdapter:
          ipfsGatewayEndpoint: https://ipfs-gateway.fluence.dev
          networkId: "123420000220"
          diamondContract: "0x72D09226141645949D09191bC42Da7de88535461"
