apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
spec:
  values:
    operator:
      image:
        repository: "docker.fluence.dev/lightmare"
        # tag: "feat-new-deals-getter-4423a59-2455-1@sha256:f4c88cf4662a70b819cc89c6ee9f0964c8153fe34e331b017d9012e03444f9fc"
      config:
        logLevel: "debug"
        print: true
        chainAdapter:
          networkId: "123420000220"
          diamondContract: "0x72D09226141645949D09191bC42Da7de88535461"
          httpEndpoint: https://rpc.stage.fluence.dev
          wsEndpoint: wss://ws.stage.fluence.dev
        ccp:
          proofPeriod: "1 year"
        k8s:
          privateVlanId: "${PRIVATE_VLAN_ID}"
        nodes:
          nodeSelector: beam/id
