apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  service:
    spec:
      ports:
        - name: http
          port: 80
          targetPort: 3000
  config:
    server:
      root_url: "http://grafana.${CLUSTER_ID}.${NETWORK}"
    log:
      mode: "console"
    users:
      allow_sign_up: "false"
      allow_org_create: "false"
    auth:
      disable_login_form: "true"
      disable_signout_menu: "false"
    auth.generic_oauth:
      enabled: "true"
      name: "Authentik"
      auto_login: "true"
      client_id: "${GRAFANA_OIDC_CLIENT_ID}"
      client_secret: "$__env{GF_OAUTH_CLIENT_SECRET}"
      scopes: "openid profile email groups"
      auth_url: "https://authentik.cloudless.dev/application/o/authorize/"
      token_url: "https://authentik.cloudless.dev/application/o/token/"
      api_url: "https://authentik.cloudless.dev/application/o/userinfo/"
      login_attribute_path: "preferred_username"
      email_attribute_path: "email"
      name_attribute_path: "name"
      role_attribute_path: "contains(groups[*], 'grafana-admins') && 'Admin' || contains(groups[*], 'grafana-devs') && 'Editor' || 'Viewer'"
      allow_assign_grafana_admin: "true"
      use_pkce: "true"
    security:
      admin_user: fluence
      admin_password: "$__env{GF_SECURITY_ADMIN_PASSWORD}"
    analytics:
      check_for_updates: "false"
    news:
      news_feed_enabled: "false"

  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              readinessProbe:
                failureThreshold: 3
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
              env:
                - name: GF_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc
                      key: client_secret
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc
                      key: admin_password
          securityContext:
            fsGroup: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
