apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fluence-intermediate-issuer.yml
  - grafana-tls-cert.yml
  - grafana.yml
  - netbird-setupkey.yml
  - oidc-secret.yml
  - admin-bootstrap.yml
  - folders/
