---
apiVersion: netbird.io/v1alpha1
kind: SetupKey
metadata:
  name: grafana
  namespace: observability
spec:
  name: spectrum-${NETWORK}-grafana
  ephemeral: true
---
apiVersion: netbird.io/v1alpha1
kind: SidecarProfile
metadata:
  name: grafana
  namespace: observability
spec:
  setupKeyRef:
    name: grafana
  podSelector:
    matchLabels:
      netbird.io/inject: "true"
  injectionMode: Container
  containerOverride:
    command:
      - env
      - NB_DISABLE_UPDATE_SETTINGS=false
      - NB_DNS_RESOLVER_ADDRESS=127.0.0.1:53
      - /usr/local/bin/netbird-entrypoint.sh
