apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.63.0/cdi-operator.yaml
patches:
  - target:
      kind: Namespace
      name: cdi
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cdi
      $patch: delete
