---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/ingress/cert-manager/manager
  prune: false
  targetNamespace: ingress
  sourceRef:
    kind: GitRepository
    name: spectrum
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuers
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux/apps/ingress/cert-manager/issuers
  prune: false
  targetNamespace: ingress
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  dependsOn:
    - name: cert-manager
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: spectrum-vars
        optional: false
