apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-operator-config
  namespace: flux-system
spec:
  path: ./flux/apps/networking/netbird-operator-config/app
  prune: false
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: spectrum-vars
        optional: false
      - kind: ConfigMap
        name: spectrum-manual-vars
        optional: true
  dependsOn:
    - name: netbird-operator
