apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-webhook-cert
spec:
  secretName: controller-webhook-cert
  dnsNames:
    - admission-controller.fluence.svc
    - admission-controller.fluence.svc.cluster.local
  issuerRef:
    name: cloudless-crd-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudless-crd-issuer
spec:
  selfSigned: {}
