apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  labels:
    app: admission-controller
    app.kubernetes.io/name: admission-controller
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
        app.kubernetes.io/name: admission-controller
    spec:
      serviceAccountName: admission-controller
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: docker.fluence.dev/crd-admission:0.1.0-rc2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: admission-config
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP

          volumeMounts:
            - name: webhook-certs
              mountPath: /certs
              readOnly: true

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault

      volumes:
        - name: webhook-certs
          secret:
            secretName: controller-webhook-cert
