apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - validating-webhook.yml
  - certs.yml

configMapGenerator:
  - name: admission-config
    namespace: fluence
    envs:
      - config.env

images:
- name: docker.fluence.dev/crd-admission
  newName: docker.fluence.dev/crd-admission
  newTag: main-1bab8b2-2929-1
