apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crd-validation-webhook
  annotations:
    cert-manager.io/inject-ca-from: "fluence/admission-webhook-cert"
webhooks:
  - name: validate.cloudless.dev
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: fluence
        name: admission-controller
        path: "/validate"
      caBundle: ""
    rules:
      - apiGroups: ["cloudless.dev"]
        apiVersions: ["v1alpha1"]
        resources: ["*"]
        operations: ["CREATE", "UPDATE"]
        scope: Cluster
