apiVersion: netbird.io/v1
kind: NBSetupKey
metadata:
  name: router
  namespace: networking
spec:
  managementURL: "https://netbird.infrahub.cloudless.dev"
  secretKeyRef:
    name: netbird-setup-key
    key: setupKey
