apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-operator
  namespace: flux-system
spec:
  path: ./flux/apps/networking/netbird-operator/app
  prune: false
  targetNamespace: networking
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
