apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluence-crd
  namespace: flux-system
spec:
  path: ./kustomize/crd
  prune: false
  targetNamespace: fluence
  sourceRef:
    kind: GitRepository
    name: lightmare
    namespace: flux-system
  interval: 5h
  retryInterval: 2m
  timeout: 5m
