apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  values:
    sources:
      - gateway-httproute
    policy: sync
    txtOwnerId: "K8S-KABAT-STAGE"
    domainFilters:
      - "cloudless.dev"
    provider: cloudflare
    extraArgs:
      - --exclude-record-types=AAAA
    serviceMonitor:
      enabled: true
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: token
