apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: public
  namespace: kube-system
spec:
  config: |
    {"cniVersion":"0.3.0","type":"kube-ovn","server_socket":"/run/openvswitch/kube-ovn-daemon.sock","provider":"public.kube-system.ovn"}
