apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flux/repositories

  - ../../flux/apps/kube-system
  - ../../flux/apps/flux-system
  - ../../flux/apps/kubevirt
  - ../../flux/apps/system
  - ../../flux/apps/observability

  - ../../flux/apps/lightmare
