apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yml
  - nic-sync.yml
patches:
  - path: satellite.yml
configMapGenerator:
  - name: linstor-satellite-lvm-conf
    files:
      - lvm.conf
generatorOptions:
  disableNameSuffixHash: true
