apiVersion: v1
kind: Service
metadata:
  name: grafana-netbird
  annotations:
    netbird.io/expose: "true"
    netbird.io/resource-name: "grafana.${CLUSTER_ID}.${NETWORK}"
    netbird.io/groups: "spectrum-${NETWORK}"
    netbird.io/policy-name: "grafana-access"
    netbird.io/policy-source-groups: "support,admins"
    netbird.io/policy-protocol: "tcp"
    netbird.io/policy-ports: "3000"
spec:
  type: ExternalName
  externalName: grafana-service.observability.svc.cluster.local
  ports:
    - protocol: TCP
      port: 3000
