apiVersion: v1
kind: Service
metadata:
  name: grafana-netbird
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: "grafana"
spec:
  type: ExternalName
  externalName: grafana-service.observability.svc.cluster.local
  ports:
    - protocol: TCP
      port: 3000
