apiVersion: v1
kind: Service
metadata:
  name: kube-oidc-proxy
  namespace: kube-oidc-proxy
spec:
  selector:
    app: kube-oidc-proxy
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
