apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  controller:
    enabled: true

  csiController:
    enabled: true

  csiNode:
    enabled: true

  nfsServer:
    enabled: false
  
  highAvailabilityController:
    enabled: true
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: talos-override
spec:
  podTemplate:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: storage/linstor
        workload.default.ovn.kubernetes.io/logical_switch: linstor
    spec:
      initContainers:
        - name: drbd-shutdown-guard
          $patch: delete
        - name: drbd-module-loader
          $patch: delete
      containers:
        - name: linstor-satellite
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LS_CONTROLLERS
              value: http://linstor-controller:3370
        - name: replication-nic-reconciler
          image: linstor-satellite
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LS_CONTROLLERS
              value: http://linstor-controller:3370
          command:
            - /bin/sh
            - -ceux
            - |
              LOG=/var/log/replication-setup.log

              retry() { max="10"; shift; n=0; until "$@"; do n=$((n+1)); [ "$n" -ge "$max" ] && return 1; sleep 2; done; }

              net1_ip() {
                ip -4 -o addr show dev net1 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1
              }

              echo "[$(date -Iseconds)] reconciler start" >>"$LOG"

              while true; do
                REPL_IP="$(net1_ip || true)"
                [ -n "${REPL_IP:-}" ] || { sleep 2; continue; }

                retry 60 linstor node list >/dev/null 2>&1 || { sleep 5; continue; }
                retry 60 linstor node show "$NODE_NAME" >/dev/null 2>&1 || { sleep 5; continue; }

                if linstor -m node interface list "$NODE_NAME" 2>/dev/null \
                   | grep -q "\"name\"[[:space:]]*:[[:space:]]*\"replication\""; then
                  if ! linstor node interface modify "$NODE_NAME" replication --ip "$REPL_IP" >/dev/null 2>&1; then
                    linstor node interface delete "$NODE_NAME" replication >/dev/null 2>&1 || true
                    linstor node interface create "$NODE_NAME" replication "$REPL_IP" >/dev/null 2>&1 || true
                  fi
                else
                  linstor node interface create "$NODE_NAME" replication "$REPL_IP" >/dev/null 2>&1 || true
                fi

                sleep 15
              done
          volumeMounts:
            - name: shared-data
              mountPath: /var/log
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: run-systemd-system
        $patch: delete
      - name: run-drbd-shutdown-guard
        $patch: delete
      - name: systemd-bus-socket
        $patch: delete
      - name: lib-modules
        $patch: delete
      - name: usr-src
        $patch: delete
      - name: etc-lvm-backup
        hostPath:
          path: /var/etc/lvm/backup
          type: DirectoryOrCreate
      - name: etc-lvm-archive
        hostPath:
          path: /var/etc/lvm/archive
          type: DirectoryOrCreate
# ---
# apiVersion: piraeus.io/v1
# kind: LinstorSatelliteConfiguration
# metadata:
#   name: use-replication-network
# spec:
#   properties:
#     - name: PrefNic
#       value: replication
