apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: stack
spec:
  retentionPeriod: "1"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
