apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lightmare
spec:
  values:
    operator:
      config:
        chainAdapter:
          networkId: "9999999"
          diamondContract: "0xb05C35133C01C7193F09079eAeF97F693aE0E552"
          httpEndpoint: https://rpc.mainnet.fluence.dev
          wsEndpoint: wss://ws.mainnet.fluence.dev
        ccp:
          proofPeriod: "7 min"
        k8s:
          privateVlanId: "${PRIVATE_VLAN_ID}"
        nodes:
          nodeSelector: beam/id
