apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.1/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.1/kubevirt-cr.yaml
patches:
  - patch: |-
      apiVersion: kubevirt.io/v1
      kind: KubeVirt
      metadata:
        name: kubevirt
        namespace: kubevirt
      spec:
        configuration:
          developerConfiguration: 
            featureGates:
              - CPUManager
  - target:
      kind: Namespace
      name: kubevirt
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kubevirt
      $patch: delete
