apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vm-stack
  namespace: flux-system
spec:
  path: ./flux/apps/observability/victoria-metrics/stack
  prune: true
  targetNamespace: observability
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: vm-operator
    - name: grafana-operator-crd
