apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  controller:
    enabled: true

  csiController:
    enabled: true

  csiNode:
    enabled: true

  nfsServer:
    enabled: false
  
  highAvailabilityController:
    enabled: true
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: talos-override
spec:
  podTemplate:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: storage/linstor
        workload.default.ovn.kubernetes.io/logical_switch: linstor
    spec:
      initContainers:
        - name: drbd-shutdown-guard
          $patch: delete
        - name: drbd-module-loader
          $patch: delete
      containers:
        - name: linstor-satellite
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LS_CONTROLLERS
              value: http://linstor-controller:3370
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    (
                      set -eu

                      # IPv4 on net1
                      REPLICATION_IP="$(ip -4 addr show net1 | awk '/inet /{print $2}' | cut -d/ -f1)"
                      [ -n "${REPLICATION_IP:-}" ] || exit 0

                      # Wait for controller, then for THIS node to exist
                      until linstor node list >/dev/null 2>&1; do sleep 5; done
                      until linstor node list "$NODE_NAME" >/dev/null 2>&1; do sleep 3; done

                      # Ensure/refresh 'replication' interface
                      if linstor node interface list "$NODE_NAME" | awk 'NR>2{print $2}' | grep -q '^replication$'; then
                        CUR_IP="$(linstor node interface list "$NODE_NAME" | awk '$2=="replication"{print $3}')"
                        [ "$CUR_IP" = "$REPLICATION_IP" ] || {
                          linstor node interface delete "$NODE_NAME" replication || true
                          linstor node interface create "$NODE_NAME" replication "$REPLICATION_IP"
                        }
                      else
                        linstor node interface create "$NODE_NAME" replication "$REPLICATION_IP"
                      fi
                    ) >/var/log/replication-setup.log 2>&1 &
                    exit 0
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: run-systemd-system
        $patch: delete
      - name: run-drbd-shutdown-guard
        $patch: delete
      - name: systemd-bus-socket
        $patch: delete
      - name: lib-modules
        $patch: delete
      - name: usr-src
        $patch: delete
      - name: etc-lvm-backup
        hostPath:
          path: /var/etc/lvm/backup
          type: DirectoryOrCreate
      - name: etc-lvm-archive
        hostPath:
          path: /var/etc/lvm/archive
          type: DirectoryOrCreate
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: use-replication-network
spec:
  properties:
    - name: PrefNic
      value: replication
