apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: linstor
spec:
  config: '{"cniVersion":"0.3.0","provider":"linstor.storage.ovn","server_socket":"/run/openvswitch/kube-ovn-daemon.sock","type":"kube-ovn"}'
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: linstor
spec:
  cidrBlock: 10.17.147.0/24
  protocol: IPv4
  provider: linstor.storage.ovn
  logicalGateway: true
  vlan: ${STORAGE_VLAN} # need beam to add it to the spectrum-vars.yml configmap
