---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/system/envoy/app
  prune: true
  targetNamespace: system
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-proxy
  namespace: flux-system
spec:
  path: ./flux/apps/system/envoy/proxy
  prune: true
  targetNamespace: system
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: envoy
