---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator-crd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/system/grafana-operator/crd
  prune: true
  targetNamespace: system
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  path: ./flux/apps/system/grafana-operator/app
  prune: true
  targetNamespace: system
  sourceRef:
    kind: GitRepository
    name: spectrum
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: grafana-operator-crd
