apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crd-operator
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: crd-operator
    namespace: fluence
  values:
    controller:
      image:
        repository: "docker.fluence.dev/crd-controller"
        tag: "0.6.3"
      persistence:
        storageClassName: lvm-thin-r2

    api:
      image:
        repository: "docker.fluence.dev/crd-api"
        tag: "0.8.1"

    admission:
      image:
        repository: "docker.fluence.dev/crd-admission"
        tag: "0.3.2"
