apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crd-operator
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: crd-operator
    namespace: fluence
  values:
    controller:
      image:
        repository: "containers.cloudless.dev/release/crd-controller"
        tag: "0.9.0"
      persistence:
        storageClassName: lvm-thin-r2

    api:
      image:
        repository: "containers.cloudless.dev/release/crd-api"
        tag: "0.11.2"

    admission:
      image:
        repository: "containers.cloudless.dev/release/crd-admission"
        tag: "0.5.2"

    vmApi:
      image:
        repository: "containers.cloudless.dev/release/crd-vm-api"
        tag: "0.3.6"
      jwt:
        jwksUrl: "https://api.testnet.fluence.dev/v1/internal/.well_known/jwks.json"
