apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crd-operator
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: crd-operator
    namespace: fluence
  values:
    controller:
      config:
        LTM_CRD_CTRL__PUBLIC_NETWORK__SUBNETS: '["subnet-66cd1ddf-3f7e-4d1c-9439-714c15d971b7"]'
      image:
        repository: "docker.fluence.dev/crd-controller"
        tag: main-a930e27-3092-1

    api:
      image:
        repository: "docker.fluence.dev/crd-controller"
        tag: main-a930e27-3092-1

    admission:
      image:
        repository: "docker.fluence.dev/crd-controller"
        tag: main-a930e27-3092-1
