apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 10m
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: local-path-beam-config
      valuesKey: values.yaml
      optional: false
  values:
    image:
      repository: docker.io/rancher/local-path-provisioner
      tag: v0.0.32
    storageClass:
      create: true
      defaultClass: true
