apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubevirt-virt-launcher-alert
spec:
  groups:
    - name: kubevirt.virt_launcher.alerts
      rules:
      - alert: KubeVirtVMStuckInStartingState
        expr: |
          (
            time() - kubevirt_vmi_info{phase="Pending"}
          ) > 300
        for: 5m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM stuck in starting state"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} has been stuck in Pending state for more than 5 minutes."
          runbook_url: "https://kubevirt.io/monitoring/runbooks/KubeVirtVMStuckInStartingState.html"
          
      - alert: KubeVirtVMIExcessiveMigrations
        expr: |
          count by (name, exported_namespace) (
            increase(kubevirt_vmi_migrations_total{name!=""}[24h])
          ) > 3
        for: 5m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VMI has excessive migrations"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} has migrated {{ $value }} times in the last 24 hours."
          runbook_url: "https://kubevirt.io/monitoring/runbooks/KubeVirtVMIExcessiveMigrations.html"
          
      - alert: VirtLauncherVMHighMemoryUsage
        expr: kubevirt_virt_launcher:memory_usage_ratio > 0.9
        for: 10m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM memory usage is high"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is using {{ $value | humanizePercentage }} of available memory."
          
      - alert: VirtLauncherVMHighCPUUsage
        expr: kubevirt_virt_launcher:cpu_usage_seconds:rate5m > 0.9
        for: 15m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM CPU usage is high"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is using {{ $value | humanizePercentage }} CPU."
          
      - alert: VirtLauncherVMNetworkErrorsHigh
        expr: |
          (
            rate(kubevirt_vmi_network_receive_errors_total[5m])
            +
            rate(kubevirt_vmi_network_transmit_errors_total[5m])
          ) > 10
        for: 5m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM network errors are high"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} has {{ $value }} network errors per second."
          
      - alert: VirtLauncherVMStorageErrorsHigh
        expr: |
          (
            rate(kubevirt_vmi_storage_read_errors_total[5m])
            +
            rate(kubevirt_vmi_storage_write_errors_total[5m])
          ) > 5
        for: 5m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM storage errors are high"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} has {{ $value }} storage errors per second."
          
      - alert: VirtLauncherContainerMemoryExceedsRequest
        expr: |
          (
            kubevirt_virt_launcher:container_memory_usage_bytes
            /
            (kube_pod_container_resource_requests{pod=~"virt-launcher-.*", container="compute", resource="memory"} > 0)
          ) > 1.2
        for: 10m
        labels:
          severity: critical
          component: virt-launcher
        annotations:
          summary: "VM container memory usage exceeds request"
          description: "VM pod {{ $labels.pod }} is using {{ $value | humanizePercentage }} of requested memory. VM may be OOMKilled."
          
      - alert: VirtLauncherMigrationTakingTooLong
        expr: kubevirt_vmi_migration_data_remaining_bytes > 0
        for: 30m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM migration taking too long"
          description: "VMI {{ $labels.name }} migration has {{ $value | humanizeBytes }} remaining after 30 minutes."
          
      - alert: VirtLauncherHighVMDensityPerNode
        expr: kubevirt_virt_launcher:vmi_count_by_node > 20
        for: 10m
        labels:
          severity: info
          component: virt-launcher
        annotations:
          summary: "High VM density per node"
          description: "Node {{ $labels.node }} is running {{ $value }} VMs. Consider load balancing."
          
      - alert: VirtLauncherVMPhaseStuck
        expr: |
          (
            time() - kubevirt_vmi_info{phase!="Running",phase!="Succeeded"}
          ) > 600
        for: 5m
        labels:
          severity: warning
          component: virt-launcher
        annotations:
          summary: "VM stuck in non-running phase"
          description: "VMI {{ $labels.name }} in namespace {{ $labels.exported_namespace }} has been in {{ $labels.phase }} phase for more than 10 minutes."
