apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubevirt-virt-launcher-recording
spec:
  groups:
    - name: kubevirt.virt_launcher.recording_rules
      interval: 30s
      rules:
      # Basic VMI metrics
      - record: kubevirt_virt_launcher:vmi_count_total
        expr: count(kubevirt_vmi_info)
        
      - record: kubevirt_virt_launcher:vmi_count_by_phase
        expr: count by (phase) (kubevirt_vmi_info)
        
      - record: kubevirt_virt_launcher:vmi_count_by_node
        expr: count by (node) (kubevirt_vmi_info)
        
      - record: kubevirt_virt_launcher:vmi_count_by_namespace
        expr: count by (exported_namespace) (kubevirt_vmi_info)
        
      # VM resource usage
      - record: kubevirt_virt_launcher:cpu_usage_seconds:rate5m
        expr: rate(kubevirt_vmi_vcpu_seconds_total[5m])
        
      - record: kubevirt_virt_launcher:memory_resident_bytes
        expr: kubevirt_vmi_memory_resident_bytes
        
      - record: kubevirt_virt_launcher:memory_available_bytes
        expr: kubevirt_vmi_memory_available_bytes
        
      - record: kubevirt_virt_launcher:memory_unused_bytes
        expr: kubevirt_vmi_memory_unused_bytes
        
      # Network metrics
      - record: kubevirt_virt_launcher:network_receive_bytes:rate5m
        expr: rate(kubevirt_vmi_network_receive_bytes_total[5m])
        
      - record: kubevirt_virt_launcher:network_transmit_bytes:rate5m
        expr: rate(kubevirt_vmi_network_transmit_bytes_total[5m])
        
      - record: kubevirt_virt_launcher:network_receive_packets:rate5m
        expr: rate(kubevirt_vmi_network_receive_packets_total[5m])
        
      - record: kubevirt_virt_launcher:network_transmit_packets:rate5m
        expr: rate(kubevirt_vmi_network_transmit_packets_total[5m])
        
      # Storage metrics
      - record: kubevirt_virt_launcher:storage_read_bytes:rate5m
        expr: rate(kubevirt_vmi_storage_read_bytes_total[5m])
        
      - record: kubevirt_virt_launcher:storage_write_bytes:rate5m
        expr: rate(kubevirt_vmi_storage_write_bytes_total[5m])
        
      - record: kubevirt_virt_launcher:storage_read_times:rate5m
        expr: rate(kubevirt_vmi_storage_read_times_total[5m])
        
      - record: kubevirt_virt_launcher:storage_write_times:rate5m
        expr: rate(kubevirt_vmi_storage_write_times_total[5m])
        
      # Migration metrics
      - record: kubevirt_virt_launcher:migration_data_remaining_bytes
        expr: kubevirt_vmi_migration_data_remaining_bytes
        
      - record: kubevirt_virt_launcher:migration_data_processed_bytes
        expr: kubevirt_vmi_migration_data_processed_bytes
        
      - record: kubevirt_virt_launcher:migration_dirty_memory_rate_bytes
        expr: kubevirt_vmi_migration_dirty_memory_rate_bytes
        
      # Memory pressure and usage ratios
      - record: kubevirt_virt_launcher:memory_usage_ratio
        expr: |
          (
            kubevirt_vmi_memory_resident_bytes
            /
            (kubevirt_vmi_memory_resident_bytes + kubevirt_vmi_memory_available_bytes)
          )
          
      # Container resource usage for virt-launcher pods
      - record: kubevirt_virt_launcher:container_memory_usage_bytes
        expr: container_memory_working_set_bytes{pod=~"virt-launcher-.*", container="compute"}
        
      - record: kubevirt_virt_launcher:container_cpu_usage:rate5m
        expr: rate(container_cpu_usage_seconds_total{pod=~"virt-launcher-.*", container="compute"}[5m])
