apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-operator
spec:
  interval: 2h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/grafana/helm-charts/alloy-operator
  ref:
    tag: 0.8.0
