apiVersion: v1
kind: Service
metadata:
  name: linstor-controller-metrics
  labels:
    app: linstor-controller
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: linstor-controller
    app.kubernetes.io/name: piraeus-datastore
  ports:
    - name: prometheus
      port: 3370
      targetPort: api
