apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linstor-satellite
  labels:
    app: linstor-satellite
    scrape: "true"
spec:
  endpoints:
    - port: prometheus
  namespaceSelector:
    matchNames:
      - storage
  selector:
    matchLabels:
      app: linstor-satellite
