apiVersion: v1
kind: Service
metadata:
  name: linstor-satellite-metrics
  labels:
    app: linstor-satellite
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: linstor-satellite
    app.kubernetes.io/name: piraeus-datastore
  ports:
    - name: prometheus
      port: 9942
      targetPort: prometheus
