apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daemonset.yml
  - service.yml
  - service-monitor.yml
configMapGenerator:
  - name: loop-janitor
    files:
      - janitor.py
generatorOptions:
  disableNameSuffixHash: true
