apiVersion: v1
kind: Service
metadata:
  name: loop-janitor-metrics
  labels:
    app: loop-janitor
spec:
  clusterIP: None
  selector:
    app: loop-janitor
  ports:
    - name: prometheus
      port: 9943
      targetPort: prometheus
