apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/apps/flux-system/flux-instance/app
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: spectrum
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: spectrum-vars
        optional: false
  dependsOn:
    - name: flux-operator
